(function(){
'use strict';
const D=ParselData,E=ParselEngine,$=id=>document.getElementById(id),SAVE='son-parsel-game-v1',PROFILE='son-parsel-profile-v1';
let state=null,selected=null,targets=[],source='offer',map='plain',preview=null,catalogFilter='all',profile={games:0,best:0,completed:[]},replaceAction=null;
function read(key){try{return JSON.parse(localStorage.getItem(key));}catch{return null;}}
const saved=read(SAVE);if(E.validSave(saved))state=saved;
const stored=read(PROFILE);if(stored&&Number.isInteger(stored.games)&&stored.games>=0&&Number.isFinite(stored.best)&&stored.best>=0&&Array.isArray(stored.completed))profile=stored;
function persist(){try{if(state)localStorage.setItem(SAVE,JSON.stringify(state));localStorage.setItem(PROFILE,JSON.stringify(profile));}catch{notify('Tarayıcı kayda izin vermiyor. Bu sekme açıkken oynayabilirsin.');}}
function notify(text){$('status').textContent=text;}
function element(tag,className,text){const el=document.createElement(tag);if(className)el.className=className;if(text!==undefined)el.textContent=text;return el;}
function signed(n){return (n>0?'+':'')+n;}
function showSheet(title,content){$('sheet-title').textContent=title;$('sheet-content').replaceChildren();if(typeof content==='string')$('sheet-content').append(element('p','',content));else $('sheet-content').append(content);if(!$('sheet').open)$('sheet').showModal();}
function menu(){document.body.classList.remove('playing');$('menu').hidden=false;$('game').hidden=true;$('best-score').textContent=profile.best||'—';$('games-count').textContent=profile.games;$('continue').hidden=!state;$('continue').textContent=state?.finished?'Son şehrini gör ↗':'Şehrine devam et ↗';$('maps').replaceChildren();
 for(const [i,m]of D.maps.entries()){const locked=profile.games<m.unlock,b=element('button','map-option');b.type='button';b.setAttribute('aria-pressed',String(map===m.id));b.disabled=locked;b.append(element('span','map-symbol',['▦','≋','◉','⋄'][i]));const t=element('span');t.append(element('b','',m.name),element('small','',locked?`${m.unlock} şehir sonra açılır`:'Oynamaya hazır'));b.append(t);b.onclick=()=>{map=m.id;menu();};$('maps').append(b);}
 $('map-note').textContent=D.maps.find(m=>m.id===map).description+' · İki ücretsiz kart yenileme.';
}
function openGame(){if(['full','discovery'].includes(state.mode))$('mode').value=state.mode;document.body.classList.add('playing');$('menu').hidden=true;$('game').hidden=false;clearSelection();render();}
function newGame(){const tier=$('mode').value==='full'?2:Math.min(2,profile.games);state=E.newGame({seed:crypto.getRandomValues(new Uint32Array(1))[0],map,tier});state.mode=$('mode').value;persist();openGame();notify('Bir kart seç, ardından uygun parsele dokun.');}
function requestNew(){if(state&&!state.finished){replaceAction=newGame;$('confirm-dialog').showModal();}else newGame();}
function clearSelection(){selected=null;targets=[];preview=null;source='offer';}
function perform(fn){try{state=fn();clearSelection();persist();render();}catch(e){notify(e.message);}}
function choose(id,origin='offer'){if(state.pending||state.finished)return;selected=id;source=origin;targets=[];preview=id==='subsidy'?E.preview(state,id,[]):null;render();}
function tileClick(i){if(!selected){inspect(i);return;}if(state.pending||state.finished)return;
 if(['move','swap'].includes(selected)){if(!targets.length){if(!E.isTarget(state,selected,i)){notify('Önce belediye dışındaki uygun bir binayı seç.');return;}targets=[i];preview=null;}else if(targets[0]===i){targets=[];preview=null;}else{targets=[targets[0],i];preview=E.preview(state,selected,targets);if(!preview.ok){notify(preview.error);targets=[targets[0]];preview=null;}}}
 else{targets=[i];preview=E.preview(state,selected,targets);if(!preview.ok)notify(preview.error);}
 render();if(preview?.ok){$('confirm').focus({preventScroll:true});$('selection').scrollIntoView({block:'nearest',behavior:'auto'});}
}
function renderBoard(){const board=$('board');board.replaceChildren();const allowed=selected?E.placements(state,selected):[],dest=targets.length&&['move','swap'].includes(selected)?new Set(allowed.flatMap(p=>p[0]===targets[0]?[p[1]]:selected==='swap'&&p[1]===targets[0]?[p[0]]:[])):new Set(allowed.map(p=>p[0]));const adjacent=new Set(targets.flatMap(E.neighbors));
 for(let i=0;i<36;i++){const b=state.board[i],d=D.byId[b?.id],terrain=state.terrain[i],button=element('button','tile');button.type='button';button.dataset.index=i;
 const name=b?.id==='hall'?'Belediye':d?.name||({land:'Boş parsel',water:'Su',rock:'Kayalık'}[terrain]);button.setAttribute('aria-label',`${Math.floor(i/6)+1}. satır, ${i%6+1}. sütun: ${name}${b?`, seviye ${b.level}`:''}`);
 if(b){button.classList.add('built');if(b.id==='hall')button.classList.add('hall');button.style.setProperty('--tile-color',d?D.categories[d.category].color:'#375bdd');button.append(element('span','tile-symbol',d?D.categories[d.category].symbol:'▦'),element('span','tile-code',d?.token||'BLD'));if(b.level>1)button.append(element('span','level','•'.repeat(b.level)));if(b.mods.length)button.append(element('span','modified','+'));}
 else if(terrain==='land')button.classList.add('empty');else{button.classList.add(terrain);button.textContent=terrain==='water'?'≋':'⋄';}
 if(selected){if(dest.has(i))button.classList.add('eligible');else if(!targets.includes(i))button.classList.add('unavailable');if(adjacent.has(i))button.classList.add('neighbor');if(targets.includes(i))button.classList.add('selected');}
 button.onclick=()=>tileClick(i);button.onkeydown=e=>{const shifts={ArrowLeft:-1,ArrowRight:1,ArrowUp:-6,ArrowDown:6};if(shifts[e.key]!==undefined){e.preventDefault();const next=i+shifts[e.key];if(next>=0&&next<36&&(!(e.key==='ArrowLeft'||e.key==='ArrowRight')||Math.floor(next/6)===Math.floor(i/6)))board.children[next].focus();}};board.append(button);
 }
}
function render(){const st=E.evaluate(state);$('turn').textContent=state.turn;$('money').textContent=state.coins;$('energy').textContent=signed(st.power);$('energy-box').classList.toggle('danger',st.power<0);$('population').textContent=st.pop;$('happiness').textContent=st.happy;$('income').textContent='+'+st.income;$('map-title').textContent=D.maps.find(m=>m.id===state.map).name;$('forecast-name').textContent=state.finished?'Şehir tamamlandı':D.events.find(e=>e.id===state.forecast).name;$('forecast-when').textContent=state.finished?'Son puan geçici olay etkileri olmadan hesaplandı.':`${5-(state.turn-1)%5} hamle sonra · gelir dönemi${st.power<0?' · enerji açığı geliri azaltıyor':''}`;
 const goals=state.goals.filter(g=>{const p=E.goalProgress(state,g);return p.value>=p.target;});$('goal-count').textContent=goals.length+'/3';renderBoard();$('action-area').hidden=state.finished;$('results').hidden=!state.finished;
 if(state.finished){renderResults();return;}
 $('cards').hidden=!!state.pending;$('pending').hidden=!state.pending;document.querySelector('.hand-tools').hidden=!!state.pending;document.querySelector('.hand-heading').hidden=!!state.pending;$('selection').hidden=!selected||!!state.pending;
 if(state.pending){$('pending-name').textContent=state.pending.label;$('next-turn').textContent=state.turn===30?'Şehri tamamla ↗':'Sonraki tur ↗';return;}
 $('rerolls').textContent=state.rerolls;$('reroll').disabled=state.rerolls===0;$('cards').replaceChildren();for(const id of state.offers){const d=D.byId[id],b=element('button','card'),usable=E.canUse(state,id);b.type='button';b.setAttribute('aria-pressed',String(selected===id&&source==='offer'));if(selected===id&&source==='offer')b.classList.add('selected');if(!usable)b.classList.add('unaffordable');b.style.setProperty('--card-color',D.categories[d.category].color);const top=element('div','card-top');top.append(element('span','card-symbol',D.categories[d.category].symbol));const price=element('span','card-cost',String(E.cost(state,id)));price.append(element('small','','para'));top.append(price);b.append(top,element('b','',d.name),element('small','',D.categories[d.category].name));if(!usable)b.append(element('em','',E.cost(state,id)>state.coins?'Bütçe yetersiz':'Uygun parsel yok'));b.onclick=()=>choose(id);$('cards').append(b);}
 $('reserve-button').disabled=!selected||!!state.reserve||source==='reserve';$('reserved-card').hidden=!state.reserve;$('reserved-card').textContent=state.reserve?'Rezerv · '+D.byId[state.reserve].name:'';$('reserved-card').classList.toggle('active',source==='reserve');
 if(selected){const d=D.byId[selected];$('selected-name').textContent=d.name+' · '+E.cost(state,selected)+' para';$('instruction').textContent=preview?.ok?'Etkileri kontrol et ve hamleni onayla.':d.kind==='building'?'Mavi çerçeveli boş bir parsele dokun.':selected==='subsidy'?'Sonraki binan 4 para daha ucuz.':targets.length?'Şimdi ikinci parseli seç.':d.description;
 $('effects').replaceChildren();if(preview?.ok){for(const [key,label]of Object.entries({coins:'para',pop:'nüfus',income:'gelir',happy:'mutluluk',power:'enerji'})){const value=preview.delta[key];if(value)$('effects').append(element('span','effect'+(value<0?' negative':''),`${signed(value)} ${label}`));}if(!$('effects').children.length)$('effects').append(element('span','effect','Yerleşim güncellenecek'));}
 $('confirm').disabled=!preview?.ok;$('confirm').textContent=d.kind==='building'?'Buraya yerleştir':'Projeyi uygula';}
}
function inspect(i){const b=state.board[i];if(!b){showSheet(state.terrain[i]==='land'?'Boş parsel':state.terrain[i]==='water'?'Su kenarı':'Kayalık',state.terrain[i]==='land'?'Bir bina kartı seçerek bu parsele yerleştirebilirsin.':state.terrain[i]==='water'?'Suya komşu parseller seralar, oteller ve sahil yolları için değerlidir.':'Bu parsele bina kurulamaz.');return;}if(b.id==='hall'){showSheet('Belediye','Şehrin başlangıç noktası. +4 enerji ve +6 dönem geliri sağlar. Taşınamaz veya yıkılamaz.');return;}cardDetail(b.id,i);}
function cardDetail(id,index){const d=D.byId[id],wrap=element('div');wrap.append(element('p','',d.description),element('p','tip',`${D.categories[d.category].name} · Temel maliyet ${d.cost} para`));if(index!==undefined){const b=state.board[index],st=E.evaluate(state).details[index];wrap.append(element('p','',`Seviye ${b.level} · ${st.pop} nüfus · ${st.income} gelir · ${st.happy} mutluluk`));if(b.mods.length)wrap.append(element('p','',b.mods.map(id=>D.byId[id].name).join(' · ')));}else if(d.kind==='building'){wrap.append(element('p','',`Temel değerler: ${d.pop} nüfus, ${d.income} gelir, ${signed(d.power)} enerji, ${signed(d.happy)} mutluluk.`));}showSheet(d.name,wrap);}
function catalog(){const wrap=element('div'),filters=element('div','catalog-filter');for(const [id,label]of [['all','Hepsi'],...Object.entries(D.categories).map(([id,c])=>[id,c.name]),['events','Olaylar']]){const b=element('button',catalogFilter===id?'active':'',label);b.onclick=()=>{catalogFilter=id;catalog();};filters.append(b);}wrap.append(filters);
 const items=catalogFilter==='events'?D.events:D.all.filter(d=>catalogFilter==='all'||d.category===catalogFilter);for(const d of items){const item=element('div','catalog-item'),info=element('div');item.style.setProperty('--card-color',D.categories[d.category]?.color||'#375bdd');item.append(element('span','card-symbol',D.categories[d.category]?.symbol||'◷'));info.append(element('b','',d.name));if(d.cost!==undefined)info.append(element('small','',`${d.cost} para · ${D.categories[d.category].name}`));info.append(element('p','',d.description));item.append(info);wrap.append(item);}showSheet('Şehrin seçenekleri · 50',wrap);}
function goals(){const wrap=element('div');for(const id of state.goals){const g=D.goals.find(g=>g.id===id),p=E.goalProgress(state,id),done=p.value>=p.target,item=element('div','goal'+(done?' complete':''));item.append(element('b','',(done?'✓ ':'')+g.name),element('p','',g.description));const meter=element('div','goal-meter'),bar=element('i');bar.style.width=Math.min(100,p.value/p.target*100)+'%';meter.append(bar);item.append(meter,element('small','',`${p.value} / ${p.target} · +30 puan`));wrap.append(item);}wrap.append(element('p','','Hedefler maç sonundaki şehir durumuna göre değerlendirilir.'));showSheet('Şehir hedefleri',wrap);}
function renderResults(){const score=E.score(state);$('final-score').textContent=score.total;$('result-heading').textContent=score.total>=profile.best?'Yeni bir şehir hikâyesi.':'Her şehir bir ders.';$('score-breakdown').replaceChildren();for(const [key,label]of Object.entries({population:'Nüfus',wellbeing:'Mutluluk',economy:'Ekonomi',goals:'Hedefler',energy:'Enerji açığı'})){const row=element('div','breakdown-row');row.append(element('span','',label),element('b','',signed(score[key])));$('score-breakdown').append(row);}$('result-description').textContent=`${E.evaluate(state,true).pop} nüfuslu şehrin tamamlandı. Yeni araziler ve farklı komşuluklarla bir sonraki şehrini kur.`;}
$('new-game').onclick=requestNew;$('continue').onclick=openGame;$('brand').onclick=e=>{e.preventDefault();menu();};$('game-menu').onclick=menu;$('result-home').onclick=menu;$('replay').onclick=()=>{map=state.map;newGame();};
$('replace-city').onclick=()=>{$('confirm-dialog').close();replaceAction?.();};$('keep-city').onclick=()=>$('confirm-dialog').close();$('close-sheet').onclick=()=>$('sheet').close();
$('catalog-menu').onclick=catalog;$('catalog-game').onclick=catalog;$('goals-button').onclick=goals;
$('card-info').onclick=()=>selected&&cardDetail(selected);
$('forecast').onclick=()=>{const e=D.events.find(e=>e.id===state.forecast),active=D.events.find(e=>e.id===state.activeEvent);showSheet('Gelir ve şehir olayları',`Her 5 hamlede dönem geliri bütçene eklenir. Sıradaki olay: ${e.name}. ${e.description}${active?' Şu anki dönem: '+active.name+'. '+active.description:''}`);};
$('log-button').onclick=()=>{const wrap=element('div');for(const text of state.log.length?state.log:['Şehrinin ilk hamlesi seni bekliyor.'])wrap.append(element('div','log-entry',text));showSheet('Şehir geçmişi',wrap);};
$('help').onclick=()=>{const wrap=element('div'),list=element('ol');for(const text of ['Bir kart seç, sonra uygun parsele dokun. Komşuluk yalnızca üst, alt, sağ ve soldur.','Önizlemedeki etkileri incele. Yerleştir veya projeyi uygula; sonraki turdan önce geri alabilirsin.','Her 5 hamlede gelir kazanırsın. Yaklaşan olaya hazırlan. Enerji eksiye düşerse gelir azalır.','Bir kartı rezervde saklayabilirsin. İki ücretsiz yenilemen var. Tasarruf ederek bir tur karşılığında 2 para alabilirsin.','30 tur sonunda nüfus ×8, mutluluk ×4, gelir ×3, kalan para ve hedef başına 30 puan toplanır. Her enerji açığı −8 puan.','Şehrin bu cihazda otomatik kaydedilir. Menüye dönmek oyunu silmez.'])list.append(element('li','',text));wrap.append(list);showSheet('Küçük şehir, büyük kararlar',wrap);};
$('reserve-button').onclick=()=>{const id=selected;perform(()=>E.reserve(state,id));notify('Kart rezervine alındı. Bu tur başka bir hamle yapabilirsin.');};$('reserved-card').onclick=()=>choose(state.reserve,'reserve');
$('reroll').onclick=()=>perform(()=>E.reroll(state));$('pass').onclick=()=>perform(()=>E.pass(state));$('cancel-selection').onclick=()=>{clearSelection();render();};
$('confirm').onclick=()=>{if(!preview?.ok)return;const id=selected,places=targets.slice(),origin=source;perform(()=>E.play(state,id,places,origin));notify('Hamlen hazır. İstersen geri al, istersen yeni kartları aç.');};
$('undo').onclick=()=>perform(()=>E.undo(state));$('next-turn').onclick=()=>{perform(()=>E.advance(state));if(state.finished&&!profile.completed.includes(state.id)){profile.completed.push(state.id);profile.completed=profile.completed.slice(-100);profile.games++;profile.best=Math.max(profile.best,E.score(state).total);persist();render();}notify(state.finished?'Şehrin tamamlandı.':state.log[0]||'Yeni kartların hazır.');};
window.addEventListener('pagehide',persist);menu();
})();
