// Node 22+. Runs the shipped physics and UI; DOM is stubbed, not browser visual QA.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');
const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
assert.equal(scripts.length,2);
assert(!/<(?:script|img|link)\b[^>]*(?:src|href)=/i.test(html),'Single file must remain offline');
vm.runInThisContext(scripts[0]+'\nglobalThis.P=MatchPhysics;');
const {R,BALL,STEP}=P;
// A ball must never score through the closed side, even if already slightly outside.
const closed=P.create(1);closed.balls[0].x=-R-2;closed.balls[0].y=0;closed.balls[0].vx=-P.SPEED;closed.balls[0].vy=0;P.tick(closed);assert.equal(closed.score[0],0);assert(Math.hypot(closed.balls[0].x,closed.balls[0].y)<=R-BALL+.01);assert(closed.balls[0].vx>0);
// A centered shot through the mouth scores exactly once, then respawns inside.
const shot=P.create(7);shot.angle=0;Object.assign(shot.balls[0],{x:R-15,y:0,vx:P.SPEED,vy:0});for(let i=0;i<45;i++)P.tick(shot);assert.equal(shot.score[0],1);assert.equal(shot.events.length,1);for(let i=0;i<120;i++)P.tick(shot);assert.equal(shot.score[0],1);assert(shot.balls[0].cooldown<=0);assert(Math.hypot(shot.balls[0].x,shot.balls[0].y)<R);
// A shot clipping a post is blocked (ball radius must fit through the opening).
const post=P.create(8);post.angle=0;const a=P.HALF-.025;Object.assign(post.balls[0],{x:(R-BALL-1)*Math.cos(a),y:(R-BALL-1)*Math.sin(a),vx:P.SPEED*Math.cos(a),vy:P.SPEED*Math.sin(a)});for(let i=0;i<25;i++)P.tick(post);assert.equal(post.score[0],0);
// Equal-mass ball collision separates centers and reverses a head-on approach.
const hit=P.create(12);Object.assign(hit.balls[0],{x:-12,y:0,vx:P.SPEED,vy:0});Object.assign(hit.balls[1],{x:12,y:0,vx:-P.SPEED,vy:0});P.tick(hit);assert(hit.balls[0].vx<0&&hit.balls[1].vx>0);assert(hit.balls[1].x-hit.balls[0].x>=BALL*2);
function run(seed){const m=P.create(seed);for(let i=0;i<11000&&!m.finished;i++){P.tick(m);for(const b of m.balls){assert(Number.isFinite(b.x+b.y+b.vx+b.vy));assert(Math.hypot(b.x,b.y)<R+BALL+3,'Ball escaped without being scored');}}assert(m.finished);assert.equal(m.time,90);assert.equal(m.score[0]+m.score[1],m.events.length);const score=m.score.slice();P.tick(m);assert.deepEqual(m.score,score);return m;}
const scores=[];for(let seed=1;seed<=60;seed++)scores.push(run(seed).score);assert.deepEqual(run(77).events,run(77).events,'Same seed must replay identically');assert(new Set(scores.map(s=>s.join(':'))).size>5,'Different seeds should vary');console.log('60 full matches:',JSON.stringify({averageGoals:scores.reduce((n,s)=>n+s[0]+s[1],0)/scores.length,firstTen:scores.slice(0,10)}));
// Exercise actual UI event handlers and requestAnimationFrame timing.
class El{constructor(id=''){this.id=id;this.style={setProperty(){}};this.dataset={};this.attrs={};this.children=[];this.handlers={};this.hidden=false;this.value='';this.tagName='DIV';this.classList={add(){},remove(){}};}setAttribute(k,v){this.attrs[k]=String(v)}append(...c){this.children.push(...c)}replaceChildren(...c){this.children=[...c]}addEventListener(k,fn){this.handlers[k]=fn}focus(){document.activeElement=this}setCustomValidity(v){this.invalid=v}reportValidity(){return !Object.values(els).some(e=>e.invalid)}fire(k){this.handlers[k]?.({preventDefault(){}})}}
const els={};for(const m of html.matchAll(/id="([^"]+)"/g))els[m[1]]=new El(m[1]);
const themeEls=['super','champions','europa'].map(t=>{const e=new El();e.dataset.theme=t;return e});
const docHandlers={};global.document={hidden:false,body:new El(),documentElement:new El(),activeElement:null,getElementById(id){assert(els[id],`Missing element ${id}`);return els[id]},createElement:()=>new El(),createElementNS:()=>new El(),querySelectorAll:()=>themeEls,addEventListener:(k,fn)=>docHandlers[k]=fn};global.window=global;global.matchMedia=()=>({matches:false});let callback;global.requestAnimationFrame=fn=>callback=fn;let seed=800;Object.defineProperty(global,'crypto',{value:{getRandomValues(a){a[0]=seed++;return a}},configurable:true});
Object.assign(els.home,{value:'Galatasaray',tagName:'INPUT'});els.away.value='Fenerbahçe';els['home-color'].value='#dd5c63';els['away-color'].value='#e7e9e3';els['predict-home'].value='1';els['predict-away'].value='1';
vm.runInThisContext(scripts[1]);let now=0;function advance(n,hz=60){for(let i=0;i<n;i++){now+=1000/hz;callback(now)}}
assert.equal(marbleDiagnostics.state,'menu');for(const [i,key]of ['super','champions','europa'].entries()){themeEls[i].fire('click');assert.equal(document.body.dataset.theme,key);assert.equal(themeEls[i].attrs['aria-pressed'],'true');}
els.home.value='   ';els.setup.fire('submit');assert.equal(marbleDiagnostics.state,'menu');els.home.value='Galatasaray';els.home.fire('input');els.setup.fire('submit');assert.equal(marbleDiagnostics.state,'playing');assert.equal(els['home-name'].textContent,'Galatasaray');assert.equal(els['league-name'].textContent,'UEFA Avrupa Ligi');advance(180);els.pause.fire('click');const paused=marbleDiagnostics.time;advance(80);assert.equal(marbleDiagnostics.time,paused);els.pause.fire('click');advance(80);assert(marbleDiagnostics.time>paused);
document.hidden=true;docHandlers.visibilitychange();assert.equal(marbleDiagnostics.state,'paused');document.hidden=false;els.pause.fire('click');for(let i=0;i<5600&&marbleDiagnostics.state!=='finished';i++)advance(1);assert.equal(marbleDiagnostics.state,'finished');assert.equal(els.clock.textContent,'90:00');assert.equal(els.result.hidden,false);assert.equal(els.events.children.length,marbleDiagnostics.events.length);assert.equal(els['result-title'],document.activeElement);
els.again.fire('click');assert.equal(marbleDiagnostics.state,'playing');assert.equal(marbleDiagnostics.time,0);assert.deepEqual(marbleDiagnostics.score,[0,0]);assert.equal(els.events.children.length,0);assert.equal(els['home-name'].textContent,'Galatasaray');advance(60);els.exit.fire('click');assert.equal(marbleDiagnostics.state,'menu');assert.equal(els.menu.hidden,false);assert.equal(els.home.value,'Galatasaray');
// Rendering frame rate must not change simulated results for the same seed.
function uiAtRate(hz){seed=900;els.setup.fire('submit');for(let i=0;i<hz*92&&marbleDiagnostics.state!=='finished';i++)advance(1,hz);assert.equal(marbleDiagnostics.state,'finished');return marbleDiagnostics.events;}
assert.deepEqual(uiAtRate(30),uiAtRate(144));
console.log('PASS: offline syntax, closed boundary, goals/respawn, goalposts, collisions, 60 matches, deterministic seeds, themes, input validation, UI scoring, pause/resume, background pause, results, replay and 30/144 Hz agreement. Browser/GPU visual QA not performed.');
